version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: veera_offboarding_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: offboarding_db
    ports:
      - "2500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: veera_offboarding_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3830:3830"
    volumes:
      - ./Backend:/app

  frontend:
    build: ./FrontEnd
    container_name: veera_offboarding_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8047:80"

  hr:
    build: ./HR
    container_name: veera_offboarding_hr
    restart: always
    depends_on:
      - backend
    ports:
      - "8048:80"

volumes:
  pgdata:

